version: '2'

services:
    simple-vision:
        image: python3-runner:latest
        network_mode: "host"
        ipc: "host"
        volumes:
        - /tmp:/tmp
        - .:/opt/sources
        working_dir: /opt/sources/simple-vision
        command: "./simple-vision.py"
        environment:
        - PYTHONUNBUFFERED=1 # fix python prints

    simple-control:
        image: python3-runner:latest
        network_mode: "host"
        volumes:
        - .:/opt/sources
        working_dir: /opt/sources/simple-control
        command: "./simple-control.py"
        environment:
        - PYTHONUNBUFFERED=1 # fix python prints
